//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnfGefB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gefährdungsfaktoren
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gefährdungsfaktoren()
        {
            this.Anforderungen = new HashSet<Anforderungen>();
        }
    
        public int ID { get; set; }
        public int Kategorie { get; set; }
        public int Nummer { get; set; }
        public string Gefährdungsfaktor { get; set; }
        public string Merkmale { get; set; }
    
        public virtual GefährdungsfaktorenKategorien GefährdungsfaktorenKategorien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anforderungen> Anforderungen { get; set; }
    }
}
