//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnfGefB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GefährdungsfaktorenKategorien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GefährdungsfaktorenKategorien()
        {
            this.Gefährdungsfaktoren = new HashSet<Gefährdungsfaktoren>();
        }
    
        public int Nummer { get; set; }
        public string Text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gefährdungsfaktoren> Gefährdungsfaktoren { get; set; }
    }
}
