//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnfGefB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gesetze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gesetze()
        {
            this.Anforderungen = new ObservableListSource<Anforderungen>();
            this.Paragraphen = new ObservableListSource<Paragraphen>();
        }
    
        public int ID { get; set; }
        public int Typ { get; set; }
        public string Gesetz { get; set; }
        public string Kurzform { get; set; }
        public System.DateTime Stand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Anforderungen> Anforderungen { get; set; }
        public virtual Rechtstypen Rechtstypen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Paragraphen> Paragraphen { get; set; }
    }
}
