//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnfGefB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paragraphen
    {
        public int ID { get; set; }
        public int GesetzID { get; set; }
        public int Paragraph { get; set; }
        public string Zusatz { get; set; }
        public string Titel { get; set; }
        public string Text { get; set; }
    
        public virtual Gesetze Gesetze { get; set; }
    }
}
