//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnfGefB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BE_Rechtslage_GefaehrdungsbeurteilungEntities : DbContext
    {
        public BE_Rechtslage_GefaehrdungsbeurteilungEntities()
            : base("name=BE_Rechtslage_GefaehrdungsbeurteilungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anforderungen> Anforderungen { get; set; }
        public virtual DbSet<Gesetze> Gesetze { get; set; }
        public virtual DbSet<Rechtstypen> Rechtstypen { get; set; }
        public virtual DbSet<Paragraphen> Paragraphen { get; set; }
        public virtual DbSet<Bezug> Bezug { get; set; }
        public virtual DbSet<Gefährdungsfaktoren> Gefährdungsfaktoren { get; set; }
        public virtual DbSet<GefährdungsfaktorenKategorien> GefährdungsfaktorenKategorien { get; set; }
    }
}
