//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bregau_Auditplaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VerbindungString {
            get {
                return ((string)(this["VerbindungString"]));
            }
            set {
                this["VerbindungString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?><AESDataSet xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema""><Key>WDdmQU9OT21LenJicGNSWnc5OEhjQ2JHYnh1c1l6Skx6a1lxZStBTCtjQT0=</Key><IV>eWIxZnVoU1VoZXNQclF5bm4vV2UyUT09</IV><Message>EOTYxGDlPwKIbPaB5ZJHvwJDihqOnN44DYCWd+SCr5NWFYaw+76JzzfRvm/1x3hxBx5zAuwfZwc54WjcXjTdlIm4XsNqB2Pl82ZUpgT60nBprP+D1IqWDNuHp5igrTCobutvPnpaPN+2Bzw9CStpJM7o5I1J0H9om6IC6e6PX1uJ9lSbjlV6oLgEf+FVDWj0</Message></AESDataSet>")]
        public string Verbindung {
            get {
                return ((string)(this["Verbindung"]));
            }
        }
    }
}
